# Generated by Django 4.1.6 on 2023-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Visualization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
