# Generated by Django 3.2.3 on 2024-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualization', '0005_auto_20240611_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
