# Generated by Django 3.2.3 on 2024-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualization', '0006_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='FProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('contributors', models.CharField(blank=True, max_length=100, null=True)),
                ('mentors', models.CharField(blank=True, max_length=150, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('year', models.JSONField(blank=True, default=True)),
            ],
        ),
    ]
